[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "About"
  id = "about-us"
  url = "/about/"
  weight = 2
  identifier = "about"

[[main]]
  name = "Child"
  url = "/child/"
  identifier = "child"
  parent = "about"
  weight = 2

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 5