defaultSeverity: warning
extends:
    - stylelint-config-standard
    - stylelint-config-recommended
    - stylelint-config-sass-guidelines
plugins:
  - stylelint-scss
rules:
  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
      - if
      - else
  block-no-empty: true
  color-hex-case: lower
  color-hex-length: short
  color-no-invalid-hex: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-trailing-semicolon: always
  function-calc-no-unspaced-operator: true
  function-url-no-scheme-relative: true
  function-url-quotes: null
  length-zero-no-unit: true
  no-duplicate-at-import-rules: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  property-no-unknown: true
  rule-empty-line-before:
    - always
    - ignore:
      - after-comment
      - first-nested
      - inside-block
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
        ng-deep
  scss/at-rule-no-unknown: true
  scss/dollar-variable-colon-space-after: always
  scss/dollar-variable-colon-space-before: never
  scss/operator-no-unspaced: true
  shorthand-property-no-redundant-values: true
  string-quotes: single
  unit-case: lower
  unit-no-unknown:
    - true
    - ignoreUnits:
      - /^[-+][\d$(]/
  value-keyword-case: null
  indentation: null
  max-nesting-depth: 5
  selector-class-pattern: null
  no-empty-source: null
  order/properties-alphabetical-order: null
  number-leading-zero: never
  max-empty-lines: 3
  comment-whitespace-inside: never
  no-invalid-position-at-import-rule: null
  declaration-empty-line-before: null
  scss/dollar-variable-pattern: null
  selector-max-compound-selectors: 5
  no-descending-specificity: null
  declaration-property-value-allowed-list: 
    - object: 
      -unprefixed-property-name: 
        - [array, of, values]