title = "NB Template Static Site"
baseURL = "https://nb-template-site-static.netlify.app/"
languageCode = "en-gb"
enableRobotsTXT = true
publishDir = "public"
uglyURLs = false
disableHugoGeneratorInject = true
canonifyURLs = false
disableAliases = true
enableEmoji = true
enableGitInfo = false
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

paginate = 7
rssLimit = 10

[author]
	name = "NB Communication"

[params]
	strapline = "NB Template Static Site"
	email = "administrator@nbcommunication.com"
	dateFormat = "02 Jan 2006"
	analyticsID = ""
	clientName = "NB Communication"
	size = "small"
	instantPage = true

[params.dev]
  live = false

[outputs]
	home = ["HTML"]
	section = ["HTML"]

[sitemap]
	changefreq = "weekly"
	filename = "sitemap.xml"
	priority = 0.5

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  contributor = "contributors"

[RelPermalinks]
  blog = "/blog/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/uikit/dist/js"
    target = "assets/js/"
  [[module.mounts]]
    source = "node_modules/mmenu-js/dist/"
    target = "assets/js/"
  [[module.mounts]]
    source = "node_modules/instant.page/"
    target = "assets/js/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    id = "about-us"
    url = "/about/"
    weight = 2
    identifier = "about"

  [[menu.main]]
    name = "Child"
    url = "/child/"
    identifier = "child"
    parent = "about"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
