title = "NB Template Static Site"
baseURL = "https://nb-template-site-static.netlify.app/"
languageCode = "en-gb"
publishDir = "public"
uglyURLs = false
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[author]
	name = "NB Communication"

[params]
	strapline = "NB Template Static Site"
	email = "administrator@nbcommunication.com"
	dateFormat = "02 Jan 2006"
	analyticsID = ""

[params.dev]
  live = false

[markup.goldmark.renderer]
	unsafe = true

[outputs]
	home = ["HTML"]
	section = ["HTML"]

[sitemap]
	filename = "sitemap.xml"