[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'self';"

[context.production.environment]
  HUGO_VERSION = "0.87.0"

[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.87.0"
  NODE_VERSION = "14"
  RUBY_VERSION = "2.7.1"

[context.production]
  command = "npx hugo --gc --minify && npx netlify-lambda build assets/lambda"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npx hugo --gc --minify && npx netlify-lambda build assets/lambda"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "npx rimraf public resources functions && npx hugo server --bind=0.0.0.0 --disableFastRender"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
