backend:
  name: git-gateway
  branch: master

media_folder: "static/media"
public_folder: "/media"

logo_url: https://brand.nbcommunication.com/logo/web/nb_logo.png

title: "NB"
dateForm: "2.1.2006"

# Fields
fields:
  # template
  - template: &template {
    label: "Template",
    name: template,
    widget: hidden,
    default: default
  }
  # menu
  - menu: &menu {
    label: "Menu",
    name: menu,
    widget: hidden,
    default: main
  }
  # weight
  - weight: &weight {
    label: "Menu Index",
    name: weight,
    widget: number,
    default: 10,
    valueType: int,
    min: 1
  }
  # title
  - title: &title {
    label: "Title",
    name: title,
    widget: string
  }
  # headline
  - headline: &headline {
    label: "Headline",
    name: headline,
    required: false,
    hint: "If entered, this will be used on the page itself instead of the title given above.",
    widget: string
  }
  # intro
  - intro: &intro {
    label: "Intro",
    name: intro,
    required: false,
    hint: "A short introductory paragraph to the page content.",
    widget: text
  }
  # body
  - body: &body {
    label: "Content",
    name: body,
    required: false,
    widget: markdown
  }
  # images
  # @todo - not allowing multiple?
  - images: &images {
    label: "Images",
    name: images,
    required: false,
    widget: image
  }
  # date_pub
  - date_pub: &date_pub {
    label: "Publish Date",
    name: "publishDate",
    widget: "datetime"
  }
  # tags
  - tags: &tags {
    label: "Tags",
    name: "tags",
    required: false,
    widget: "list"
  }
  # blocks
  - blocks: &blocks {
    label: "Content Blocks",
    name: blocks,
    widget: list,
    types: [
      {
        label: "Text",
        name: text,
        required: false,
        widget: object,
        fields: [
          *body
        ]
      },
      {
        label: "Gallery",
        name: gallery,
        widget: object,
        fields: [
          {
            label: "Title",
            name: title,
            required: false,
            widget: string
          },
          *images,
          {
            label: "Caption",
            name: caption,
            required: false
          }
        ]
      },
      {
        label: "Slideshow",
        name: slideshow,
        widget: object,
        fields: [
          {
            label: "Title",
            name: title,
            required: false,
            widget: string
          },
          *images
        ]
      },
      {
        label: "Embed",
        name: embed,
        widget: object,
        fields: [
          {
            label: "Title",
            name: title,
            required: false,
            widget: string
          },
          {
            label: "Intro",
            name: intro,
            required: false,
            widget: text
          },
          {
            label: "HTML Code",
            name: html,
            widget: text
          }
        ]
      }
    ]
  }
  - display: &display {
    label: "Display",
    name: group_display,
    collapsed: true,
    hint: "These fields allow you to control how your page is displayed on other pages of the website, such as in listings on the homepage or gateway pages.",
    widget: object,
    fields: [
      {
        label: "Banner Image",
        name: banner,
        required: false,
        widget: image
      },
      {
        label: "Page Summary",
        name: summary,
        required: false,
        hint: "A short description of the page.",
        widget: text
      },
      {
        label: "Thumbnail Image",
        name: thumb,
        required: false,
        widget: image
      }
    ]
  }
  - social: &social {
    label: "Social",
    name: group_social,
    collapsed: true,
    hint: "These fields allow you to optimise how your page displays when shared on social media.",
    widget: object,
    fields: [
      {
        label: "Title",
        name: social_title,
        required: false,
        hint: "The title used when sharing this page on social media. If empty, the SEO title (specified or automatically generated) will be used.",
        widget: string
      },
      {
        label: "Description",
        name: social_desc,
        required: false,
        hint: "The short description used when sharing this page on social media. If empty, the SEO Description (specified or automatically generated) will be used.",
        widget: text
      },
      {
        label: "Image",
        name: social_image,
        required: false,
        hint: "The thumbnail image used when sharing this page on social media.",
        widget: image
      }
    ]
  }
  - seo: &seo {
    label: "SEO",
    name: group_seo,
    collapsed: true,
    hint: "These fields allow you to optimise how your site is displayed on search engines.",
    widget: object,
    fields: [
      {
        label: "Title",
        name: seo_title,
        required: false,
        hint: "The title used in search engine listings. For most pages, a title is automatically generated title in the format: {title} | {sitename}",
        widget: string
      },
      {
        label: "Description",
        name: seo_desc,
        required: false,
        hint: "A short description of the page, used in search engine listings.",
        widget: text
      }
    ]
  }

# Templates
collections:
  # single
  - name: "gateway"
    label: "Gateway"
    description: ""
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - << : *template
            default: home
          - *menu
          - *title
          - *headline
          - *intro
          - *display
          - *social
          - *seo
          - *weight
      - label: "News"
        name: "news"
        file: "content/news.md"
        fields:
          - << : *template
            default: posts
          - *menu
          - *title
          - *headline
          - *intro
          - *display
          - *social
          - *seo
          - *weight
  # default
  - name: "default"
    label: "Page"
    description: ""
    folder: "content"
    filter: {field: "template", value: default}
    create: true
    fields:
      - << : *template
        default: default
      - *menu
      - *title
      - *headline
      - *intro
      - *body
      - *display
      - *social
      - *seo
      - *weight
  # post
  - name: "posts"
    label: "Post"
    description: ""
    folder: "content/news"
    filter: {field: "template", value: post}
    create: true
    fields:
      - << : *template
        default: post
      - *title
      - *headline
      - *date_pub
      - *tags
      - *intro
      - *body
      - *display
      - *social
      - *seo
  # contact
  - name: "contact"
    label: "Contact"
    description: ""
    files:
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - << : *template
            default: contact
          - *menu
          - *title
          - *headline
          - *intro
          - *body
          - *display
          - *social
          - *seo
          - *weight
  # legal
  - name: "legal"
    label: "Legal"
    description: ""
    folder: "content"
    filter: {field: "template", value: legal}
    create: false
    delete: false
    fields:
      - << : *template
        default: legal
      - *title
      - *headline
      - *body
      - *seo
  # internal
  - name: "internal"
    label: "Internal"
    description: ""
    files:
      - label: "Sitemap"
        name: "sitemap"
        file: "content/sitemap.md"
        fields:
          - << : *template
            default: sitemap
          - *title
          - *intro
          - *seo
      - label: "NB Styleguide"
        name: "nb-styleguide"
        file: "content/nb.styleguide.md"
        fields:
          - << : *template
            default: nb-styleguide
          - *title
          - *headline
          - *intro
          - *body
          - *images
          - *display
          - *social
          - *seo
      - label: "NB Styleguide (Blocks)"
        name: "nb-styleguide-blocks"
        file: "content/nb.styleguide-blocks.md"
        fields:
          - << : *template
            default: nb-styleguide-blocks
          - *title
          - *headline
          - *intro
          - *blocks
          - *display
          - *social
          - *seo
module:
  imports:
    - path: github.com/UtkarshVerma/hugo-modules/svg-icon-system